version: '3.2'
services:

    minio:
        image: minio/minio:RELEASE.2022-11-08T05-27-07Z
        command: server /data --console-address ":9001"
        ports:
            - "9001:9000"
            - "9002:9001"

    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"